[package]
name = "tangram_linker"
version = "0.0.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
async-recursion = { workspace = true }
fnv = { workspace = true }
futures = { workspace = true }
goblin = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tangram_client = { workspace = true }
tangram_error = { workspace = true }
tangram_wrapper = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
xattr = { workspace = true }
