[package]
name = "tangram_vfs_test"
version = "0.0.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
tangram_client = { workspace = true }
tangram_error = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
