name: Tag Packages

on:
  push:
    branches: [ "main" ]

env:
  BUN_VERSION: 1.1.43

jobs:
  tag-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out workflow repository
      uses: actions/checkout@v4
      
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ env.BUN_VERSION }}
    
    - name: Install Tangram
      run: curl -fsSL https://tangram.dev/install.sh | sh

    - name: Tag and push all packages
      shell: bash
      run: |
        bun run auto -p
      
